<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <StartupObject>Upsinator.Startup</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\settings-icon-2.png" />
    <None Remove="Resources\settings-icon-3.png" />
    <None Remove="Resources\settings-icon.png" />
    <None Remove="Resources\settings_wrench_01.png" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="{215d64d2-031c-33c7-96e3-61794cd1ee61}">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>4</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>215d64d2-031c-33c7-96e3-61794cd1ee61</Guid>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\settings-icon-2.png" />
    <Resource Include="Resources\settings-icon-3.png" />
    <Resource Include="Resources\settings-icon.png" />
    <Resource Include="Resources\settings_wrench_01.png" />
  </ItemGroup>

</Project>
